# Generated by Django 4.2.7 on 2024-10-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_wishlist_review_productfaq_notification_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='category.jpg', null=True, upload_to='category'),
        ),
    ]
